replicaCount: 2

image:
  repository: 519361062262.dkr.ecr.us-east-2.amazonaws.com/trade-repo
  tag: latest-v2
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 3000  # change to whatever port your app actually listens on

ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
  path: /

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
