name: Deploy to Amazon ECR
on:
  workflow_dispatch:
env:
  AWS_REGION: us-east-2
  ECR_REPOSITORY: trade-repo
  GHCR_IMAGE: ghcr.io/tdfaluyi/trading-platform:latest  
  
jobs:
  deploy:
    name: Pull from GHCR & Push to ECR
    runs-on: ubuntu-latest
    permissions:
     contents: read
     id-token: write
     packages: read

    steps:
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Pull image from GHCR
        run: |
          docker pull ${{ env.GHCR_IMAGE }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ${{ env.GHCR_IMAGE }}
          format: 'table'
          severity: 'CRITICAL,HIGH'
          exit-code: '0'
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Tag and push image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
         docker tag ghcr.io/tdfaluyi/trading-platform:latest $ECR_REGISTRY/$ECR_REPOSITORY:latest
         docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
